import { categories } from "enums/Categories";
import { IProduct } from "interfaces/ProductInterface";
import image1 from 'assets/global/shoes-153310.png'

const bootsItems: IProduct[] = [
    {
        id: '00000000000000000',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000001',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000002',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000003',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000004',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000005',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000006',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000007',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000008',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000009',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000010',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000011',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000012',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000013',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000014',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000015',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000016',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000017',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000018',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000019',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000020',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000021',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000022',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000023',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000024',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000025',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000026',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000027',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000028',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000029',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000030',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000031',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000032',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000033',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
    {
        id: '00000000000000034',
        name: 'BUTY ZIMOWE MĘSKIE SPORTOWE OCIEPLONE HKR', 
        content: 'Solidne wykonanie\nOdporne na każdą pogodę, buty są wygodne, ciepłe i lekkie.\nWzmocniona konstrukcja w okolicy pięty oraz palców.\nPodeszwa wykonana z grubej pianki na antypoślizgowym spodzie.\nWnętrze ocieplone ciepłym miękkim misiem.\nFason bardzo ładnie prezentuje się na nodze.',
        price: 149.99,
        image: image1,
    },
];

const underwearItems: IProduct[] = [];
const trousersItems: IProduct[] = [];
const dressesItems: IProduct[] = [];
const socksItems: IProduct[] = [];
const glovesItems: IProduct[] = [];
const jacketsItems: IProduct[] = [];
const tshirtsItems: IProduct[] = [];

export const categoriesLists = {
    [categories.BOOTS]: bootsItems,
    [categories.UNDERWEAR]: underwearItems,
    [categories.TROUSERS]: trousersItems,
    [categories.DRESSES]: dressesItems,
    [categories.SOCKS]: socksItems,
    [categories.GLOVES]: glovesItems,
    [categories.JACKETS]: jacketsItems,
    [categories.T_SHIRTS]: tshirtsItems,
};